repos:
  - repo: https://github.com/ambv/black
    rev: "22.8.0"
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: "v3.8.3"
    hooks:
      - id: reorder-python-imports
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [
          flake8-bugbear,
        ]
