name: Linux tests

on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Use Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3"
      - name: Poetry install
        run: poetry install
      - name: pre-commit setup
        run: |
          poetry run pre-commit install
          poetry run pre-commit install-hooks
      - name: Run pre-commit
        run: |
          poetry run pre-commit run -a
  tests:
    name: ${{ matrix.python }} tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Use Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3"
      - name: Poetry install
        run: poetry install
      - name: Run Python tests
        run: |
          poetry env info
          poetry run pytest --cov=deep_collections --doctest-modules -v  --cov-report=term --cov-report=xml
      - name: Publish coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
